import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'BILLIE EILISH - HAPPIER THAN EVER - CD',
      slug: 'BILLIE EILISH - HAPPIER THAN EVER - CD',
      category: 'CD',
      image:
        '/images/billie-eilish-happier-than-ever-dia-cd_686b2f3fad3343efbe6bf2d0cd568c80_grande.webp',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 560,
      brand: 'US-UK',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'DOJA CAT - PLANET HER - ALBUM',
      slug: 'DOJA CAT - PLANET HER - ALBUM',
      category: 'Album',
      image: '/images/pic2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 380,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "TYLER SWIFT - RED (TAYLOR'S VERSION)",
      slug: "TYLER SWIFT - RED (TAYLOR'S VERSION)",
      category: 'Album',
      image: '/images/Asset 19.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1350,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'LANA DEL REY-CHEMTRAILS OVER THE COUNTRY CLUB-VINYL LP',
      slug: 'LANA DEL REY-CHEMTRAILS OVER THE COUNTRY CLUB-VINYL LP',
      category: 'Album',
      image: '/images/pic3.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 930,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'CHARLIE XCX - CRASH - ĐĨA CD',
      slug: 'CHARLIE XCX - CRASH - ĐĨA CD',
      category: 'CD',
      image:
        '/images/charli-xcx-crash-dia-cd_3e55692bddc743d596cc5ec826ccc762_grande.webp',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1100,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'TONY BENNETT & LADY GAGA - LOVE FOR SALE - ĐĨA CD',
      slug: 'TONY BENNETT & LADY GAGA - LOVE FOR SALE - ĐĨA CD',
      category: 'CD',
      image: '/images/pic6.jpg',
      isFeatured: true,
      featuredImage:
        '/images/tony-bennett-lady-gaga-love-for-sale-target-dia-cd_daf6228d6f8c4f6fa1f5e6e246bfe3f1_grande.webp',
      price: 380,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'ED SHEERAN - = (EQUAL) - ĐĨA CD',
      slug: 'ED SHEERAN - = (EQUAL) - ĐĨA CD',
      category: 'CD',
      image: '/images/Asset 16.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 335,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "CAMILA CAMELO - DON'T GO YET",
      slug: "CAMILA CAMELO - DON'T GO YET",
      category: 'Album',
      image: '/images/pic2.jpg',
      isFeatured: true,
      featuredImage:
        '/images/camila-romance-cover-1-signed-co-chu-ky-dia-cd_b22700292f3a4bc2ae46de432385bae3_grande.webp',
      price: 600,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'LANA DEL REY - BLUE BANISTERS - CD',
      slug: 'LANA DEL REY - BLUE BANISTERS - CD',
      category: 'CD',
      image: '/images/pic4.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 400,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'OLIVIA RODRIGO - SOUR - ALBUM',
      slug: 'OLIVIA RODRIGO - SOUR - ALBUM',
      category: 'Album',
      image: '/images/pic5.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 400,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'LORDE - SOLAR POWER - VINYL LP',
      slug: 'LORDE - SOLAR POWER - VINYL LP',
      category: 'Album',
      image: '/images/pic6.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1440,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'DUA LIPA - FUTURE NOSTALGIA - CD',
      slug: 'DUA LIPA - FUTURE NOSTALGIA - CD',
      category: 'CD',
      image: '/images/pic7.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 900,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'BRUNO MARS - AN EVENING WITH SILK SONIC',
      slug: 'BRUNO MARS - AN EVENING WITH SILK SONIC',
      category: 'Album',
      image: '/images/pic8.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 350,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'THE WEEKND - DAWN FM - VINYL LP ',
      slug: 'THE WEEKND - DAWN FM - VINYL LP ',
      category: 'Album',
      image: '/images/Asset 23.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1050,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'LANA DEL REY - VIOLET BENT BACKWARDS OVER THE GRASS - POEM BOOK',
      slug: 'LANA DEL REY - VIOLET BENT BACKWARDS OVER THE GRASS - POEM BOOK',
      category: 'Book',
      image: '/images/pic10.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 380,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },

    {
      name: 'AVRIL LAVIGNE - LOVE SUX - ĐĨA CD',
      slug: 'AVRIL LAVIGNE - LOVE SUX - ĐĨA CD',
      category: 'CD',
      image: '/images/us3.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 690,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'KESHI - GABRIEL - ĐĨA CD',
      slug: 'KESHI - GABRIEL - ĐĨA CD',
      category: 'CD',
      image: '/images/us2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 450,
      brand: 'US-UK',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'IVE - The 2nd Single Album [LOVE DIVE] (Random Ver.)',
      slug: 'IVE - The 2nd Single Album [LOVE DIVE] (Random Ver.)',
      category: 'Album',
      image: '/images/pic11.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 290,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'TAEYANG - TAEYANG 3RD ALBUM [WHITE NIGHT] (Random ver.)',
      slug: 'TAEYANG - TAEYANG 3RD ALBUM [WHITE NIGHT] (Random ver.)',
      category: 'Album',
      image: '/images/pic12.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 440,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'BIGBANG - BIGBANG MADE THE FULL ALBUM (Standard Ver.)',
      slug: 'BIGBANG - BIGBANG MADE THE FULL ALBUM (Standard Ver.)',
      category: 'Album',
      image: '/images/pic13.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 450,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'EXO - [Filmlive Japan Tour -Exo Planet 2021-] (2Blu-ray) (Japanese Version)',
      slug: 'EXO - [Filmlive Japan Tour -Exo Planet 2021-] (2Blu-ray) (Japanese Version)',
      category: 'CD',
      image: '/images/pic14.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 2100,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'CLASS:y - 1st Mini Album Y [CLASS IS OVER] ',
      slug: 'CLASS:y - 1st Mini Album Y [CLASS IS OVER] ',
      category: 'Album',
      image: '/images/pic15.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 250,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Red Velvet - Mini Album [The ReVe Festival 2022 - Feel My Rhythm] (Orgel Ver.) ',
      slug: 'Red Velvet - Mini Album [The ReVe Festival 2022 - Feel My Rhythm] (Orgel Ver.) ',
      category: 'Album',
      image: '/images/pic16.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 280,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'SUHO - Mini Album Vol.2 [Grey Suit] (Photobook Ver.) (Random Ver.)',
      slug: 'SUHO - Mini Album Vol.2 [Grey Suit] (Photobook Ver.) (Random Ver.)',
      category: 'PhotoBook',
      image: '/images/pic18.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 270,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'LISA - LISA 0327 PHOTOBOOK VOL.03',
      slug: 'LISA - LISA 0327 PHOTOBOOK VOL.03',
      category: 'PhotoBook',
      image: '/images/pic19.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 430,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'SUHO - Mini Album Vol.2 [Grey Suit] (Digipack Ver.)',
      slug: 'SUHO - Mini Album Vol.2 [Grey Suit] (Digipack Ver.)',
      category: 'Album',
      image: '/images/Asset 7.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 217,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'NCT DREAM - The 2nd Album [Glitch Mode] (Digipack Ver.) ',
      slug: 'NCT DREAM - The 2nd Album [Glitch Mode] (Digipack Ver.) ',
      category: 'Album',
      image: '/images/Asset 8.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 180,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Kim Sawol - Live Album [1202] (2CD)',
      slug: 'Kim Sawol - Live Album [1202] (2CD)2',
      category: 'Album',
      image: '/images/Asset 9.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 460,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "(G)I-DLE 1ST FULL ALBUM - 'I NEVER DIE'",
      slug: "(G)I-DLE 1ST FULL ALBUM - 'I NEVER DIE'",
      category: 'Album',
      image: '/images/kpop1.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 550,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'TAEYEON - INVU - ALBUM',
      slug: 'TAEYEON - INVU - ALBUM',
      category: 'Album',
      image: '/images/kpop2.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 680,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "NCT - The 3rd Album 'Universe' Photobook Ver.",
      slug: "NCT - The 3rd Album 'Universe' Photobook Ver.",
      category: 'Album',
      image: '/images/kpop3.jpg.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 460,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "SEVENTEEN - 9th Mini Album `Attacca' Op.3",
      slug: "SEVENTEEN - 9th Mini Album `Attacca' Op.3",
      category: 'Album',
      image: '/images/kpop4.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 500,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'BLACKPINK - Welcoming collection 2022 [Package + Digital Code Card]',
      slug: 'BLACKPINK - Welcoming collection 2022 [Package + Digital Code Card]',
      category: 'Album',
      image: '/images/pic17.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1450,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Kim Sawol - Live Album [1202] (2CD)',
      slug: 'Kim Sawol - Live Album [1202] (2CD)',
      category: 'Album',
      image: '/images/Asset 5.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 360,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'J_ust - EP [일_기]',
      slug: 'J_ust - EP [일_기]',
      category: 'CD',
      image: '/images/Asset 6.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 335,
      brand: 'KPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "'Bubble' Original Soundtrack Album - Sawano Hiroyuki",
      slug: "'Bubble' Original Soundtrack Album - Sawano Hiroyuki",
      category: 'Album',
      image: '/images/bubble.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 599,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Album The Book 2 - Yoasobi (Tsubame feat. Midoriizu)',
      slug: 'Album The Book 2 - Yoasobi (Tsubame feat. Midoriizu)',
      category: 'Album',
      image: '/images/pic29.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 549,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Hiten初画集『ADOLESCENCE』Art Works',
      slug: 'Hiten初画集『ADOLESCENCE』Art Works',
      category: 'ArtWorks',
      image: '/images/hiten artwork.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 649,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'The Quintessential Bride Nendoroid Nakano Miku Masumi',
      slug: 'The Quintessential Bride Nendoroid Nakano Miku Masumi',
      category: 'CD',
      image: '/images/Miku Nakano.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 799,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "Album 『Indigrotto』Endorfin. 10th Album〚 COLOURS.01 'Growing' 〛- Nardack + Nakuru Aitsuki",
      slug: "Album 『Indigrotto』Endorfin. 10th Album〚 COLOURS.01 'Growing' 〛- Nardack + Nakuru Aitsuki",
      category: 'Album',
      image: '/images/Indigrotto.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 699,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "TRUE WIRELESS STEREO EARPHONES Ichika Nakano (CV: Kana Hanazawa) - Anime 'The Quintessential Quintessential Bride ∬'",
      slug: "TRUE WIRELESS STEREO EARPHONES Ichika Nakano (CV: Kana Hanazawa) - Anime 'The Quintessential Quintessential Bride ∬'",
      category: 'HeadPhone',
      image: '/images/pic34.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 2199,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Figure Shiriasu [Azur Land] 1/8 PVC & ABS Painted Finished Product Limited',
      slug: 'Figure Shiriasu [Azur Land] 1/8 PVC & ABS Painted Finished Product Limited',
      category: 'Figure',
      image: '/images/figure 1.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 3999,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: '100 Years Doraemon Long Stories',
      slug: '100 Years Doraemon Long Stories',
      category: 'Story',
      image: '/images/pic37.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 12999,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Inugami Korone Birthday Memorial 2021 Full Set (Poster + Cup and Spoon Design + Muffler Towel + Sticker + Badge)',
      slug: 'Inugami Korone Birthday Memorial 2021 Full Set (Poster + Cup and Spoon Design + Muffler Towel + Sticker + Badge)',
      category: 'Poster',
      image: '/images/pic38.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 2099,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Hololive Production Calendar 2022',
      slug: 'Hololive Production Calendar 2022',
      category: 'Calendar',
      image: '/images/pic39.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 349,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Pandora Box Collectors Box Set - Jun Mochizuki',
      slug: 'Pandora Box Collectors Box Set - Jun Mochizuki',
      category: 'Pandora',
      image: '/images/pic41.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 5499,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "Sword Art Online Platinum Collector's Edition",
      slug: "Sword Art Online Platinum Collector's Edition",
      category: 'Collection',
      image: '/images/SAO.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 949,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'One Piece SA-MAXIMUM Monkey D. Luffy Gear 4 Snakeman Hình ONE PIECE...',
      slug: 'One Piece SA-MAXIMUM Monkey D. Luffy Gear 4 Snakeman Hình ONE PIECE...',
      category: 'OnePiece',
      image: '/images/Asset 10.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 399,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'One Piece Thousand Sunny Wano Country Edition Ver. Mô hình nhựa BAS5060269',
      slug: 'One Piece Thousand Sunny Wano Country Edition Ver. Mô hình nhựa BAS5060269',
      category: 'OnePiece',
      image: '/images/Asset 11.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 350,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "Phiên bản điện ảnh 'Demon Slayer' Infinite Train Edition [Phiên bản thường]",
      slug: "Phiên bản điện ảnh 'Demon Slayer' Infinite Train Edition [Phiên bản thường]",
      category: 'CD',
      image: '/images/Asset 12.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 599,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Your Lie in April DVD trọn bộ BOX1 (Tập 1-11) Anime Your Lie in April DVD nhập khẩu',
      slug: 'Your Lie in April DVD trọn bộ BOX1 (Tập 1-11) Anime Your Lie in April DVD nhập khẩu',
      category: 'CD',
      image: '/images/Asset 13.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 460,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Gia đình điệp viên tập 2 Tatsuya Endo SPY x FAMILY SPY FAMILY',
      slug: 'Gia đình điệp viên tập 2 Tatsuya Endo SPY x FAMILY SPY FAMILY',
      category: 'CD',
      image: '/images/Asset 14.png ',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 280,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'A Silent Voice Original Soundtrack- Limited Edition Other vinyls',
      slug: 'A Silent Voice Original Soundtrack- Limited Edition Other vinyls',
      category: 'SoundTrack',
      image: '/images/anime1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1150,
      brand: 'JPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'Hoàng Dũng x Môi Điên - Áo Sweater 25',
      slug: 'Hoàng Dũng x Môi Điên - Áo Sweater 25',
      category: 'Áo',
      image: '/images/vpop1.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 787,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'TẠ QUANG THẮNG - Ở GIỮA CUỘC ĐỜI (TIMES EXCLUSIVE) - ĐĨA CD',
      slug: 'TẠ QUANG THẮNG - Ở GIỮA CUỘC ĐỜI (TIMES EXCLUSIVE) - ĐĨA CD',
      category: 'CD',
      image: '/images/vpop13.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 990,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "BINZ'S OVER SCREEN MERCURY COUGAR GRAPHIC T-SHIRT - BLACK",
      slug: "BINZ'S OVER SCREEN MERCURY COUGAR GRAPHIC T-SHIRT - BLACK",
      category: 'Áo',
      image: '/images/vpop2.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 990,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "BINZ'S BANDANA",
      slug: "BINZ'S BANDANA",
      category: 'Áo',
      image: '/images/vpop3.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 339,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'BINZ’S CAP - MERCURY COUGAR HANDMADE GRAPHIC ',
      slug: 'BINZ’S CAP - MERCURY COUGAR HANDMADE GRAPHIC ',
      category: 'Cap',
      image: '/images/vpop4.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 449,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'CÁ HỒI HOANG - DÂY ĐEO VA X 250 LANYARD',
      slug: 'CÁ HỒI HOANG - DÂY ĐEO VA X 250 LANYARD',
      category: 'Strap',
      image: '/images/vpop5.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 90,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'GIGI HƯƠNG GIANG - DU HÀNH VÀO TÂM TRÍ (LIMITED BOXSET) - ĐĨA CD',
      slug: 'GIGI HƯƠNG GIANG - DU HÀNH VÀO TÂM TRÍ (LIMITED BOXSET) - ĐĨA CD',
      category: 'CD',
      image: '/images/vpop6.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 599,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: "ISAAC - PHOTOBOOK 2019 'NGÀY KHÔNG EM' (CÓ CHỮ KÝ + TẶNG POSTCARD + ĐĨA CD)",
      slug: "ISAAC - PHOTOBOOK 2019 'NGÀY KHÔNG EM' (CÓ CHỮ KÝ + TẶNG POSTCARD + ĐĨA CD)",
      category: 'CD',
      image: '/images/vpop7.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 280,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'BỨC TƯỜNG - CON ĐƯỜNG KHÔNG TÊN (CASSETTE TAPE) - BĂNG CASSETTE',
      slug: 'BỨC TƯỜNG - CON ĐƯỜNG KHÔNG TÊN (CASSETTE TAPE) - BĂNG CASSETTE',
      category: 'Cassete',
      image: '/images/vpop10.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 350,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'MEOFW LẠC - RỪNG BÊ TÔNG - ĐĨA CD',
      slug: 'MEOFW LẠC - RỪNG BÊ TÔNG - ĐĨA CD',
      category: 'CD',
      image: '/images/vpop11.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 250,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'LÊ CÁT TRỌNG LÝ - CÂY LẶNG GIÓ NGỪNG (TIMES EXCLUSIVE) - ĐĨA CD',
      slug: 'LÊ CÁT TRỌNG LÝ - CÂY LẶNG GIÓ NGỪNG (TIMES EXCLUSIVE) - ĐĨA CD',
      category: 'CD',
      image: '/images/vpop12.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 280,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'GIGI HƯƠNG GIANG - DU HÀNH VÀO TÂM TRÍ (STANDARD VER.) - ĐĨA CD',
      slug: 'GIGI HƯƠNG GIANG - DU HÀNH VÀO TÂM TRÍ (STANDARD VER.) - ĐĨA CD',
      category: 'CD',
      image: '/images/vpop9.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 280,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'THÁI ĐINH - BÀI HÁT SỐ 8 (STANDARD) - ĐĨA CD',
      slug: 'THÁI ĐINH - BÀI HÁT SỐ 8 (STANDARD) - ĐĨA CD',
      category: 'CD',
      image: '/images/pic43.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 250,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'LÊ CÁT TRỌNG LÝ - LÊ CÁT TRỌNG LÝ (DELUXE EDITION - COKE BOTTLE CLEAR VINYL LP) - ĐĨA THAN',
      slug: 'LÊ CÁT TRỌNG LÝ - LÊ CÁT TRỌNG LÝ (DELUXE EDITION - COKE BOTTLE CLEAR VINYL LP) - ĐĨA THAN',
      category: 'Đĩa',
      image: '/images/pic44.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1050,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'HÀ ANH TUẤN - CUỐI NGÀY NGƯỜI ĐÀN ÔNG MỘT MÌNH (VINYL LP) ',
      slug: 'HÀ ANH TUẤN - CUỐI NGÀY NGƯỜI ĐÀN ÔNG MỘT MÌNH (VINYL LP) ',
      category: 'Đĩa',
      image: '/images/pic45.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 1200,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'NGUYÊN HÀ - HÔM QUA HÔM NAY & SAU NÀY - ĐĨA CD',
      slug: 'NGUYÊN HÀ - HÔM QUA HÔM NAY & SAU NÀY - ĐĨA CD',
      category: 'CD',
      image: '/images/pic46.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 300,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'MIN - 50/50 ( THE FIRST ALBUM / STANDARD VER. ) - ĐĨA CD',
      slug: 'MIN - 50/50 ( THE FIRST ALBUM / STANDARD VER. ) - ĐĨA CD',
      category: 'CD',
      image: '/images/pic47.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 280,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
    {
      name: 'CÁ HỒI HOANG - NGÀY ẤY VÀ SAU NÀY (∨∧) (CASSETTE TAPE) - BĂNG CASSETTE',
      slug: 'CÁ HỒI HOANG - NGÀY ẤY VÀ SAU NÀY (∨∧) (CASSETTE TAPE) - BĂNG CASSETTE',
      category: 'Cassete',
      image: '/images/vpop8.png',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 350,
      brand: 'VPOP',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular',
    },
  ],
};
export default data;
